export default {
  // Fetch stats
  FETCH_STATS: 'FETCH_STATS',
  FETCH_STATS_SUCCESS: 'FETCH_STATS_SUCCESS',
  FETCH_STATS_FAIL: 'FETCH_STATS_FAIL',

  // Convert
  CONVERT: 'CONVERT',
  CONVERT_SUCCESS: 'CONVERT_SUCCESS',
  CONVERT_FAIL: 'CONVERT_FAIL',
};
