export default {
  // Fetch rates
  FETCH_RATES: 'FETCH_RATES',
  FETCH_RATES_SUCCESS: 'FETCH_RATES_SUCCESS',
  FETCH_RATES_FAIL: 'FETCH_RATES_FAIL',

  // Fetch currencies
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_CURRENCIES_SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
  FETCH_CURRENCIES_FAIL: 'FETCH_CURRENCIES_FAIL',
};
